#! /bin/bash

#error check arguments
if [ $# -ne 1 ]; then
	echo "Icorrect call."
	echo "Use: $0 <start|stop>"
	exit
fi

if [ "$1" == "start" ]; then
	python3 app.py &
	cd ../Tango
	source bin/activate
	python restful-tango/server.py 5001 &
	deactivate

elif [ "$1" == "stop" ]; then
	flask_proc=$(ps -u | grep -i "$(pgrep -u ${USER} python)" | grep -i "app" | awk '{print $2}')
	kill $flask_proc

	tango_proc=$(ps -u | grep -i "$(pgrep -u ${USER} python)" | grep -i "server" | awk '{print $2}')
	kill $tango_proc


else
	echo "Icorrect call."
	echo "Use: $0 <start|stop>"
	exit
fi

